# Generated by Django 5.1.5 on 2025-01-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_cartitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='name',
        ),
    ]
