# Generated by Django 5.1.5 on 2025-01-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_cartitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='name',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
