# Generated by Django 5.1.5 on 2025-02-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_cartitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='name',
        ),
    ]
